config {
    type: "assertion",
    description: "Assert that all pickup location ids in the staging tripdata details table exist in the taxi zone lookup table.",
    tags: ["data_quality"]
}

select td.fk_pickup_location_id
from ${ ref("int_staging__yellow_tripdata_details") } td
left join ${ ref("stg_nyctaxi_raw__taxi_zone_lookup") } tzl
on td.fk_pickup_location_id = tzl.location_id
where tzl.location_id is null