name: Dataform cli run
run-name: Started by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      # tags:
      #   description: Tags to run
      #   required: true
      #   default: marts
      #   type: choice
      #   options:
      #     - marts
      #     - finance
      #     - geo
      environment:
        description: Environment
        type: environment
        required: true


jobs:
  run_if:
    if: github.ref_name == 'dev' || startsWith(github.ref_name, 'release')
    runs-on: ubuntu-latest
    environment: $ENVIRONMENT
    container:
      image: node:25
    steps:
      - uses: actions/checkout@v4
      - name: Install Dataform Node.js cli
        run: npm i -g @dataform/cli@^3.0.0
      - name: Connect using Service Account
        env:
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          LOCATION: ${{ vars.LOCATION }}
          GCP_DATAFORM_SA_KEY: ${{ secrets.GCP_DATAFORM_SA_KEY }}
        run: |
          node -e "
          const creds = {
            projectId: process.env.PROJECT_ID,
            credentials: process.env.GCP_DATAFORM_SA_KEY,
            location: process.env.LOCATION
          };
          require('fs').writeFileSync('.df-credentials.json', JSON.stringify(creds));
          "
      - name: Run compile
        run: dataform compile
      - name: Run tests
        run: dataform test
      - name: Dry run
        run: dataform run --dry-run
      # - name: Run marts
      #   run: dataform run --tags "$TAGS"