name: Compile release + Run marts
run-name: Started by ${{ github.actor }}
on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened

jobs:
  run_if:
    if: github.ref_name == 'dev' || startsWith(github.ref_name, 'release')
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: node:25
    steps:
      - uses: actions/checkout@v4
      - name: Install Dataform Node.js cli
        run: npm i -g @dataform/cli@^3.0.0
      - name: Connect using Service Account
        env:
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          LOCATION: ${{ vars.LOCATION }}
          GCP_DATAFORM_SA_KEY: ${{ secrets.GCP_DATAFORM_SA_KEY }}
        run: |
          node -e "
          const creds = {
            projectId: process.env.PROJECT_ID,
            credentials: JSON.parse(process.env.GCP_DATAFORM_SA_KEY),
            location: process.env.LOCATION
          };
          require('fs').writeFileSync('.df-credentials.json', JSON.stringify(creds));
          "
      - name: Run compile
        run: dataform compile
      # - name: Run tests
      #   run: dataform test
      - name: Dry run
        run: dataform run --dry-run
      - name: Run marts
        run: dataform run --tags "marts"